name: share_social_network
description: Weeidl
version: 1.2.1
homepage: https://github.com/weeidl/share_social_network

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  flutter_svg: 1.1.0
  screenshot: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - image/
  plugin:
    platforms:
      android:
        package: com.weeidl.share_social_network
        pluginClass: SocialSharePlugin
      ios:
        pluginClass: SocialSharePlugin

